### ISSUE TITLE
tips PHP Notice:  A non well formed numeric value encountered in 

### ISSUE THREAD

**Issue by zwb121** [zkjiaaa/metamask-login#1]
![image](https://user-images.githubusercontent.com/48743242/119805150-90d39000-bf13-11eb-9b59-93b04d903982.png)
![image](https://user-images.githubusercontent.com/48743242/119805183-9b8e2500-bf13-11eb-8c01-78d635924978.png)

**Comment by zkjiaaa** [comment]
i had the same problem,u try modifying the $v variable. 

`$v  = ord(hex2bin(substr($sign, 130, 2))) - 27;`

![image](https://user-images.githubusercontent.com/28976643/119805806-296a1000-bf14-11eb-9bc6-7167f1910bf7.png)

**Comment by zwb121** [comment]
Ok, it's ok, thank you

**Comment by zkjiaaa** [comment]
the same problem,u try modifying the $v variable.

`$v = ord(hex2bin(substr($sign, 130, 2))) - 27;`

then it can work
